# build info for pyodide
package:
  name: pyevermizer
  version: 0.41.3

source:
  # this will get replaced by build-meta
  sha256: ab8117fdc8758fdfab6027eaf12ac54b2e95058018fa662d89d16d97d2f2e7a5
  url: https://github.com/black-sliver/pyevermizer/releases/download/v0.41.3/pyevermizer-0.41.3.tar.gz

build:
  # override evermizer. this is used by the build action to resolve submodules
  script: if [ -d ../../evermizer ]; then cp -rf ../../evermizer ./src/; fi
