# build info for pyodide
package:
  name: pyevermizer
  version: 0.44.0

source:
  # this will get replaced by build-meta
  sha256: 28c13bbeb6df091c0a58c1b172fdafe6741f00dc0029e64946c02688526d5b84
  url: https://github.com/black-sliver/pyevermizer/releases/download/v0.42.0/pyevermizer-0.42.0.tar.gz

build:
  # override evermizer. this is used by the build action to resolve submodules
  script: if [ -d ../../evermizer ]; then cp -rf ../../evermizer ./src/; fi
