name: Build sdist wheel

on:
  workflow_dispatch:
  workflow_call:


jobs:
  build_sdist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install requirements
      run: python -m pip install -U pip build

    - name: Build source distribution
      run: python -m build . --sdist

    - name: Test source distribution
      run: |
        python -m pip install dist/*
        python -c "import pyevermizer"

    - uses: actions/upload-artifact@v4
      with:
        name: any-sdist
        path: ./dist/*
