name: Build sdist wheel

on: workflow_dispatch

jobs:
  build_sdist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: recursive

    - uses: actions/setup-python@v2

    - name: Build source distribution
      run: |
        python -m pip install -U setuptools wheel pip
        python setup.py sdist

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*
