name: CI

# this builds against windows and linux on oldest and newest cpython we want to support whenever actual code is changed

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!doc/**'
      - '!.github/workflows/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!doc/**'
      - '!.github/workflows/**'
      - '.github/workflows/test.yaml'
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: python -m pip install build

    - run: python -m build --wheel

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.python-version }}-dist
        path: dist/*.whl

    - name: Install from source and import
      run: |
        python -m pip install .
        python -c "import pyevermizer"
