name: CI

# this builds against windows and linux on oldest and newest cpython we want to support whenever actual code is changed

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!doc/**'
      - '!.github/workflows/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!doc/**'
      - '!.github/workflows/**'
      - '.github/workflows/test.yaml'


jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true  # required for 3.12rc

    - name: Install requirements
      run: python -m pip install -U pip build

    - name: Build wheel
      run: |
        python -m build --wheel
        ls dist

    - name: Test from source
      run: |
        python -m pip install .
        python -c "import pyevermizer"

    - name: Test wheel
      shell: bash
      run: |
        python -m pip uninstall -y pyevermizer
        python -m pip install dist/*
        python -c "import pyevermizer"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.python-version }}-dist
        path: dist/*.whl


  build-sdist:
    uses: ./.github/workflows/build-sdist.yaml
