name: Test pip install

on: workflow_dispatch

env:
  TAG: v0.42.0
  VERSION: 0.42.0-1

jobs:
  pip-install-source:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, windows-latest]

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: python -m pip install build

    - name: Try pip install
      shell: bash
      run: |
        python --version
        python -m pip install https://github.com/black-sliver/pyevermizer/releases/download/$TAG/pyevermizer-$VERSION.tar.gz
